# Generated by Django 4.0 on 2022-02-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='petType',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
