# Generated by Django 4.0.2 on 2022-02-10 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_pet_pettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Animal Lover'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='content',
            field=models.TextField(verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='petAge',
            field=models.CharField(max_length=50, verbose_name='Pet Age'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='petName',
            field=models.CharField(max_length=50, verbose_name='Pet Name'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='petSpecies',
            field=models.CharField(max_length=50, verbose_name='Pet Species'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='petType',
            field=models.CharField(max_length=50, verbose_name='Pet Type'),
        ),
    ]
