# Generated by Django 4.0.2 on 2022-02-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_author_alter_pet_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Add pet's image.."),
        ),
    ]
