# Generated by Django 4.0.2 on 2022-02-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_petimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='petImage',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Add pet's image.."),
        ),
    ]
