# Generated by Django 4.0.2 on 2022-02-10 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=50, verbose_name='Pet Name')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='E-Mail')),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Phone Number')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Animal Lover')),
            ],
        ),
    ]
