# Generated by Django 4.0.2 on 2022-02-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='interest',
            field=models.CharField(blank=True, max_length=50, verbose_name='Interests'),
        ),
    ]
